// GENERATED by apps/web/scripts/sync-smartess.mjs from apps/api/src/smartess/smartess.client.ts. Do not edit.
import { createHash } from "crypto";

/**
 * Minimal client for the SmartESS / DessMonitor cloud API (api.dessmonitor.com).
 *
 * Signing (same scheme the SmartESS web app uses):
 *   login: sign = sha1(salt + sha1(password) + actionString)
 *   calls: sign = sha1(salt + secret + token + actionString)
 * where actionString is "&action=...&k=v..." exactly as sent in the URL.
 *
 * Secrets, tokens and signed URLs are never logged or put in error messages.
 */

export interface SmartessDevice {
  pn: string;
  sn: string;
  devcode: number;
  devaddr: number;
}

export interface SmartessConfig {
  baseUrl: string;
  /** Login action. When omitted, "authSource" is tried first and then "auth". */
  authAction?: string;
  username: string;
  passwordSha1: string;
  companyKey: string;
  source: string;
  /** Not needed to log in or to list the account's devices. */
  device?: SmartessDevice;
}

export interface SmartessPar {
  id: string;
  par: string;
  val: string;
  unit?: string;
}

export interface SmartessLastData {
  gts?: string;
  pars: SmartessPar[];
}

export interface SmartessDayTable {
  titles: string[];
  rows: string[][];
}

interface Session {
  token: string;
  secret: string;
  expiresAt: number;
}

interface ApiEnvelope {
  err?: number;
  desc?: string;
  dat?: unknown;
}

const APP_PARAMS: Array<[string, string]> = [
  ["_app_client_", "web"],
  ["_app_id_", "taqati"],
  ["_app_version_", "1.0.0"],
];

/**
 * Energy-storage inverters answer through querySPDeviceLastData, other device
 * types through queryDeviceLastData, and the energy-flow view carries the
 * headline PV / load / battery figures the app draws on its house picture.
 */
const READ_ACTIONS = ["querySPDeviceLastData", "queryDeviceLastData", "webQueryDeviceEnergyFlowEs"];

export const sha1 = (value: string) => createHash("sha1").update(value).digest("hex");

export function buildAction(action: string, params: Array<[string, string]>) {
  return (
    `&action=${encodeURIComponent(action)}` +
    params.map(([key, value]) => `&${key}=${encodeURIComponent(value)}`).join("")
  );
}

/**
 * A SmartESS device SN is the datalogger PN followed by the device code (4 hex
 * digits) and the device address (2 hex digits). Returns null if it does not fit.
 */
export function deviceFromSn(pn: string, sn: string): SmartessDevice | null {
  const cleanPn = pn.trim();
  const cleanSn = sn.trim();
  if (!cleanPn || !cleanSn.startsWith(cleanPn)) return null;
  const rest = cleanSn.slice(cleanPn.length);
  if (!/^[0-9a-fA-F]{6}$/.test(rest)) return null;
  return {
    pn: cleanPn,
    sn: cleanSn,
    devcode: parseInt(rest.slice(0, 4), 16),
    devaddr: parseInt(rest.slice(4), 16),
  };
}

export class SmartessApiError extends Error {
  constructor(
    readonly action: string,
    readonly code: number | undefined,
    description: string | undefined,
  ) {
    super(`SmartESS ${action} failed (err=${code ?? "unknown"}${description ? `: ${description}` : ""})`);
    this.name = "SmartessApiError";
  }
}

export class SmartessClient {
  private session?: Session;

  constructor(private readonly config: SmartessConfig) {}

  /**
   * Reads every parameter the cloud exposes for the device. Actions are tried in
   * order and their parameters merged until `isComplete` says there is enough.
   */
  async fetchLastData(isComplete?: (pars: SmartessPar[]) => boolean): Promise<SmartessLastData> {
    try {
      return await this.readAll(isComplete);
    } catch (error) {
      // A stale session is the usual reason every action fails: log in again once.
      if (error instanceof SmartessApiError && this.session) {
        this.session = undefined;
        return this.readAll(isComplete);
      }
      throw error;
    }
  }

  /**
   * Devices on the account. Energy-storage inverters are listed by
   * webQueryDeviceEs; other device types only by the general listings.
   */
  async listDevices(): Promise<SmartessDevice[]> {
    const found = new Map<string, SmartessDevice>();
    let lastError: unknown;
    for (const action of ["webQueryDeviceEs", "webQueryDevice", "queryDevices"]) {
      try {
        collectDevices(await this.call(action, [["page", "0"], ["pagesize", "50"]]), found);
      } catch (error) {
        lastError = error;
      }
      if (found.size > 0) break;
    }
    // "No such device" answers mean an empty account; anything else is a real failure.
    if (found.size === 0 && lastError && !/NOT_FOUND|NO_RECORD/i.test(String(lastError))) throw lastError;
    return [...found.values()];
  }

  /**
   * Every reading the cloud kept for one day (`date` is YYYY-MM-DD in the device
   * timezone), newest first, as a table: `titles[i]` names column `i` of each row.
   * The collector reports about every 5 minutes; a day without data is empty.
   */
  async fetchDayRows(date: string): Promise<SmartessDayTable> {
    const { device, source } = this.config;
    if (!device) throw new Error("SmartESS device is not configured");
    const base: Array<[string, string]> = [
      ["source", source],
      ["devcode", String(device.devcode)],
      ["pn", device.pn],
      ["devaddr", String(device.devaddr)],
      ["sn", device.sn],
      ["i18n", "en_US"],
      ["date", date],
    ];
    let titles: string[] = [];
    const rows: string[][] = [];
    // The service caps a page at 100 rows; a full day is about 290.
    for (let page = 0; page < 10; page += 1) {
      let dat: { total?: unknown; title?: unknown; row?: unknown };
      try {
        dat = ((await this.call("queryDeviceDataOneDayPaging", [...base, ["page", String(page)], ["pagesize", "100"]])) ?? {}) as typeof dat;
      } catch (error) {
        if (error instanceof SmartessApiError && /NO_RECORD/i.test(error.message)) break;
        throw error;
      }
      if (page === 0 && Array.isArray(dat.title)) {
        titles = dat.title.map((item) => String((item as { title?: unknown } | null)?.title ?? ""));
      }
      const pageRows = Array.isArray(dat.row) ? dat.row : [];
      for (const row of pageRows) {
        const field = (row as { field?: unknown } | null)?.field;
        if (Array.isArray(field)) rows.push(field.map((value) => String(value ?? "")));
      }
      if (pageRows.length === 0 || rows.length >= Number(dat.total ?? 0)) break;
    }
    return { titles, rows };
  }

  private async readAll(isComplete?: (pars: SmartessPar[]) => boolean): Promise<SmartessLastData> {
    const { device, source } = this.config;
    if (!device) throw new Error("SmartESS device is not configured");
    const params: Array<[string, string]> = [
      ["source", source],
      ["devcode", String(device.devcode)],
      ["pn", device.pn],
      ["devaddr", String(device.devaddr)],
      ["sn", device.sn],
      ["i18n", "en_US"],
    ];

    const pars: SmartessPar[] = [];
    let gts: string | undefined;
    let answered = false;
    let lastError: unknown;

    for (const action of READ_ACTIONS) {
      try {
        const parsed = parseLastData(await this.call(action, params));
        answered = true;
        pars.push(...parsed.pars);
        gts ??= parsed.gts;
        if (isComplete?.(pars)) break;
      } catch (error) {
        lastError = error;
      }
    }

    if (!answered) throw lastError ?? new Error("SmartESS returned no data");
    return { gts, pars };
  }

  private async authenticate(): Promise<Session> {
    const actions = this.config.authAction ? [this.config.authAction] : ["authSource", "auth"];
    // SmartESS user names are case-sensitive and phone keyboards change the case
    // silently, so an unknown user is retried in the other common spellings.
    const typed = this.config.username.trim();
    const spellings = [...new Set([typed, typed.charAt(0).toUpperCase() + typed.slice(1), typed.toLowerCase(), typed.toUpperCase()])];
    const unknownUser = (error: unknown) => /NOT_FOUND_USR/i.test(String(error));
    let firstError: unknown;
    for (const username of spellings) {
      let informative: unknown;
      for (const action of actions) {
        try {
          return await this.login(action, username);
        } catch (error) {
          firstError ??= error;
          if (!unknownUser(error)) informative ??= error;
        }
      }
      // Any other answer (wrong password, network) is about a user that exists,
      // so it is the one worth reporting and another spelling would not help.
      if (informative) throw informative;
    }
    throw firstError;
  }

  private async login(authAction: string, username: string): Promise<Session> {
    const { baseUrl, passwordSha1, companyKey, source } = this.config;
    const salt = String(Date.now());
    const action = buildAction(authAction, [
      ["usr", username],
      ["company-key", companyKey],
      ["source", source],
      ...APP_PARAMS,
    ]);
    const sign = sha1(salt + passwordSha1 + action);
    const body = await this.request(authAction, `${baseUrl}?sign=${sign}&salt=${salt}${action}`);

    const dat = body.dat as { token?: unknown; secret?: unknown; expire?: unknown } | undefined;
    if (!dat || typeof dat.token !== "string" || typeof dat.secret !== "string") {
      throw new SmartessApiError(authAction, body.err, "missing token/secret in response");
    }
    // Lifetime is reported in seconds (7 days when absent); renew a little early.
    const expireSeconds = Number(dat.expire);
    const lifetime = Number.isFinite(expireSeconds) && expireSeconds > 0 ? expireSeconds : 7 * 24 * 3600;
    return { token: dat.token, secret: dat.secret, expiresAt: Date.now() + Math.max(60, lifetime - 300) * 1000 };
  }

  private async ensureSession() {
    if (!this.session || this.session.expiresAt - Date.now() < 60_000) {
      this.session = await this.authenticate();
    }
    return this.session;
  }

  private async call(action: string, params: Array<[string, string]>): Promise<unknown> {
    const session = await this.ensureSession();
    const salt = String(Date.now());
    const actionString = buildAction(action, [...params, ...APP_PARAMS]);
    const sign = sha1(salt + session.secret + session.token + actionString);
    const url = `${this.config.baseUrl}?sign=${sign}&salt=${salt}&token=${session.token}${actionString}`;
    return (await this.request(action, url)).dat;
  }

  private async request(action: string, url: string): Promise<ApiEnvelope> {
    // SmartESS is slow and occasionally drops a request: retry once on a
    // network/timeout error, never on a real API answer.
    for (let attempt = 0; ; attempt += 1) {
      try {
        const response = await fetch(url, { signal: AbortSignal.timeout(15_000) });
        if (!response.ok) throw new SmartessApiError(action, undefined, `HTTP ${response.status}`);
        const body = (await response.json()) as ApiEnvelope;
        if (body.err !== 0) throw new SmartessApiError(action, body.err, body.desc);
        return body;
      } catch (error) {
        if (error instanceof SmartessApiError || attempt >= 1) throw error;
      }
    }
  }
}

/** Finds every object in a listing that looks like a device (has pn, sn and devcode). */
function collectDevices(node: unknown, out: Map<string, SmartessDevice>, depth = 0) {
  if (!node || typeof node !== "object" || depth > 6) return;
  if (Array.isArray(node)) {
    for (const child of node) collectDevices(child, out, depth + 1);
    return;
  }
  const item = node as Record<string, unknown>;
  const devcode = Number(item.devcode);
  const devaddr = Number(item.devaddr);
  if (typeof item.sn === "string" && item.sn && typeof item.pn === "string" && item.pn && Number.isFinite(devcode) && Number.isFinite(devaddr)) {
    out.set(item.sn, { pn: item.pn.trim(), sn: item.sn.trim(), devcode, devaddr });
    return;
  }
  for (const child of Object.values(item)) collectDevices(child, out, depth + 1);
}

/**
 * Collects every {par, val, unit} entry found anywhere in the payload. The
 * nesting differs between actions and device families, so walk it generically.
 */
export function parseLastData(dat: unknown): SmartessLastData {
  const pars: SmartessPar[] = [];
  const seen = new Set<unknown>();

  const visit = (node: unknown, depth: number) => {
    if (!node || typeof node !== "object" || depth > 6 || seen.has(node)) return;
    seen.add(node);
    if (Array.isArray(node)) {
      for (const child of node) visit(child, depth + 1);
      return;
    }
    const item = node as Record<string, unknown>;
    const label = item.par ?? item.name;
    const value = item.val ?? item.value;
    if (typeof label === "string" && label.trim() && (typeof value === "string" || typeof value === "number")) {
      pars.push({
        id: typeof item.id === "string" ? item.id : "",
        par: label.trim(),
        val: String(value),
        unit: typeof item.unit === "string" ? item.unit : undefined,
      });
      return;
    }
    for (const child of Object.values(item)) visit(child, depth + 1);
  };
  visit(dat, 0);

  const gts = dat && typeof dat === "object" ? (dat as { gts?: unknown }).gts : undefined;
  return { gts: typeof gts === "string" ? gts : typeof gts === "number" ? String(gts) : undefined, pars };
}
